// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import Foundation;
@import UIKit;
@import CoreFoundation;
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface NSBundle (SWIFT_EXTENSION(MessageKit))
@end

@class NSCoder;

SWIFT_CLASS("_TtC10MessageKit16CustomBubbleView")
@interface CustomBubbleView : UIView
@property (nonatomic) CFTimeInterval animationDuration;
@property (nonatomic) CGFloat preferredMaxLayoutWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL selected;
@property (nonatomic, readonly) BOOL isUpdating;
- (void)performBatchUpdates:(void (^ _Nonnull)(void))updateClosure animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)layoutSubviews;
@property (nonatomic, readonly) BOOL canCalculateSizeInBackground;
@end


SWIFT_CLASS("_TtC10MessageKit14FileBubbleView")
@interface FileBubbleView : UIView
@property (nonatomic) CFTimeInterval animationDuration;
@property (nonatomic) CGFloat preferredMaxLayoutWidth;
@property (nonatomic) CGFloat fileWidth;
@property (nonatomic) CGFloat fileHeight;
@property (nonatomic) CGSize fileBubbleViewSize;
@property (nonatomic) CGSize fileIconSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL selected;
@property (nonatomic, readonly) BOOL isUpdating;
- (void)performBatchUpdates:(void (^ _Nonnull)(void))updateClosure animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)layoutSubviews;
@property (nonatomic, readonly) BOOL canCalculateSizeInBackground;
@end

@class UICollectionViewLayoutAttributes;

SWIFT_CLASS("_TtC10MessageKit27MessageCollectionViewLayout")
@interface MessageCollectionViewLayout : UICollectionViewLayout
- (void)invalidateLayout;
- (void)prepareLayout;
@property (nonatomic, readonly) CGSize collectionViewContentSize;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class NSLayoutConstraint;

SWIFT_CLASS("_TtC10MessageKit21MessageViewController")
@interface MessageViewController : UIViewController <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource>
@property (nonatomic, readonly, strong) UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, strong) NSLayoutConstraint * _Null_unspecified inputContainerBottomConstraint;
@property (nonatomic) BOOL isFirstLayout;
- (UIView * _Nonnull)createInputView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerTransitionCoordinator;

@interface MessageViewController (SWIFT_EXTENSION(MessageKit))
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


@interface MessageViewController (SWIFT_EXTENSION(MessageKit))
- (BOOL)isScrolledAtBottom;
- (BOOL)isScrolledAtTop;
- (BOOL)isCloseToBottom;
- (BOOL)isCloseToTop;
- (void)scrollToBottomWithAnimated:(BOOL)animated;
- (CGRect)visibleRect;
@end

@class UICollectionViewCell;

@interface MessageViewController (SWIFT_EXTENSION(MessageKit))
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView performAction:(SEL _Nonnull)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canPerformAction:(SEL _Nonnull)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
@end


@interface MessageViewController (SWIFT_EXTENSION(MessageKit))
- (void)enqueueMessageCountReductionIfNeeded;
@property (nonatomic, readonly) double focusPosition;
@end


SWIFT_CLASS("_TtC10MessageKit15PhotoBubbleView")
@interface PhotoBubbleView : UIView
@property (nonatomic) CFTimeInterval animationDuration;
@property (nonatomic) CGFloat preferredMaxLayoutWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isUpdating;
- (void)performBatchUpdates:(void (^ _Nonnull)(void))updateClosure animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)layoutSubviews;
@property (nonatomic, readonly) BOOL canCalculateSizeInBackground;
@end


SWIFT_CLASS("_TtC10MessageKit14TextBubbleView")
@interface TextBubbleView : UIView
@property (nonatomic) CGFloat preferredMaxLayoutWidth;
@property (nonatomic) CFTimeInterval animationDuration;
@property (nonatomic) BOOL selected;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isUpdating;
- (void)performBatchUpdates:(void (^ _Nonnull)(void))updateClosure animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)layoutSubviews;
@property (nonatomic, strong) NSCache<id, id> * _Null_unspecified layoutCache;
@property (nonatomic, readonly) BOOL canCalculateSizeInBackground;
@end


@interface UIColor (SWIFT_EXTENSION(MessageKit))
+ (UIColor * _Nonnull)bma_colorWithRgb:(NSInteger)rgb;
- (UIColor * _Nonnull)bma_blendWithColor:(UIColor * _Nonnull)color;
@end


@interface UIImage (SWIFT_EXTENSION(MessageKit))
@end


@interface UIImage (SWIFT_EXTENSION(MessageKit))
@end


@interface UIImage (SWIFT_EXTENSION(MessageKit))
- (UIImage * _Nonnull)bma_tintWithColor:(UIColor * _Nonnull)color;
- (UIImage * _Nonnull)bma_blendWithColor:(UIColor * _Nonnull)color;
+ (UIImage * _Nonnull)bma_imageWithColor:(UIColor * _Nonnull)color size:(CGSize)size;
@end


@interface UIImageView (SWIFT_EXTENSION(MessageKit))
@end


@interface UIView (SWIFT_EXTENSION(MessageKit))
@end


@interface UIView (SWIFT_EXTENSION(MessageKit))
@property (nonatomic) CGRect bma_rect;
@end

#pragma clang diagnostic pop
